### ISSUE TITLE
error notification in 4.0.16 

### ISSUE THREAD

**Issue by jojo12** [astridx/pkg_agosms#101]
When I try to upload a gpxtrack, I get:
Class 'AG\Module\Agosms\Site\Helper\EasyFileUploaderHelper' not found 

(meanwhile in the J3 version, this works well.)
I wrote you this in a email too, but then I saw, I've to post it here]

**Comment by astridx** [comment]
Please have a look if this version fixes the bug: https://github.com/astridx/pkg_agosms/releases/tag/v4.0.19
