### ISSUE TITLE
Problem with markers in 4.0.22

### ISSUE THREAD

**Issue by jojo12** [astridx/pkg_agosms#104]
J!4.1.5 mod_agosm 4.0.22
![nomarker](https://user-images.githubusercontent.com/2960236/185740371-a254571d-d147-4e77-bb34-d7b25325eff0.png)
Hi, for example for start and end points there is no marker only something like placeholders (see image above)
This is in all my browsers: firefox, edge and chrome.
in special pin configuration:
if I use setting "pin with fontawesome icon" I can't see the icon in the backend (module settings), 
![noicon](https://user-images.githubusercontent.com/2960236/185741234-53c90252-5e9c-4710-8cac-8cf0c2035f6f.png)
but it is visible on the map.
if I use setting "standard" then it is shown like the first image above.

**EDIT**: ah, I see, this problem seems to be linked with t4_bs5_blank template, with cassiopeia it works fine. What can I do, if I need t4?
**EDIT2**: This problem is only when I enable CSS Optimisation and JS Optimisation! 
For me this problem is solved now! Can be closed!

**Comment by astridx** [comment]
Thanks for your research and the information here. Maybe it will help others.
