### ISSUE TITLE
not more than 90 entries in "spezielle Pin-Konfiguration"?

### ISSUE THREAD

**Issue by escuco** [astridx/pkg_agosms#105]
Hello!

I'm using the module to pin fleamarket sales locations on a map on this site:
https://flohmarkt-uelsen.de/index.php/flohmarktplan-strassenkarte

Everything worked fine (even if the loading time is increasing in the backend when opening or saving the settings due to the higher number of pins), but now I'm not able to set up more pins to the map. 

At the moment there are 90 entries. When I'm going to save one more entry, the module is terminated and the module list overview is shown. 

Is there a maximum number of entries for the pin configuration?

Joomla 3.10
Agosm 3.0.6

Thank you!

**Comment by astridx** [comment]
Salut,

The limit value for the special markers in the module is very high. It is 1000
https://github.com/astridx/pkg_agosms/blob/650a8095c2a1e73e0d9d6848e4bf621e016439f1/src/modules/mod_agosm/mod_agosm.xml#L400

I suspect that there is a limit on the server side. With debug mode turned on, I get the following message with 90 spcial markers:

`Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0`


Could `max_input_vars` also be the cause for you?



Are you already planning to upgrade to Joomla 4. Maybe in the course of this you can create a Joomla article or an Agsoms article per marker and include it in the module via a custom field. This way you don't need the special markers in the module. In this quantity they are difficult to handle.

**Comment by escuco** [comment]
Hello!

> Could `max_input_vars` also be the cause for you?

Yes, thank you, that did the trick! I've changed the value from 1500 to 2000 and now I'm able to save more markers :)

> Maybe in the course of this you can create a Joomla article or an Agsoms article per marker and include it in the module via a custom field. 

I'm going to migrate this project and three other websites to Joomla 4 this winter. After that I'll have a closer look to your proposal. At the moment I'm not sure what you mean with "an article per marker", but maybe it'll be a little clearer after the upgrade. Otherwise I would come back to you at a later time.

Thanks again for your quick reply and help!
Jan

**Comment by astridx** [comment]
Thank you very much.
For your information only. I did not create an upgrade for agosms from Joomla 3 to Joomla 4. The version for Joomla 4 is a separate/new one. That means you have to uninstall the J3 extension and install the new one. I'm happy to help with converting/transferring the "marker" data.
