### ISSUE TITLE
I do not see the Tab "Show pin for articles"

### ISSUE THREAD

**Issue by hescherb** [astridx/pkg_agosms#13]
Hallo Astrid
I do not see the Tab "Show pin for articles"
It may be not an issue. I may have missed something
![issue with module](https://user-images.githubusercontent.com/55437209/65031004-ca7f8580-d940-11e9-88e4-ce03be38ad86.jpg)
I can send you Credential for this sandbox website
If you contact me, I need a piece of code to link the connected user to the selected user/article/link whatever is the easiest
named for example "select as my shop"
•	store in variable username, Name, and shop_aid of the selected aid
•	open the actual user_session, retrieve the user_id open the corresponding tables where Vendor_name and Vendor_aid are stored
o	 and fill Vendor_name with username, Name and Vendor_aid of the selected shop etc
Do you think it is possible and can you contact me ?.
Alles gute

**Comment by astridx** [comment]
> @hescherb Für Leaflet  - WGS84 à EPSG:25833

Are you sure, that you have installed the current version?

**Comment by hescherb** [comment]
Hallo Astrid
Thanks a lot
I had download from
https://extensions.joomla.org/extensions/extension/maps-a-weather/maps-a-locations/agosm/
and now from github, it works fine
Herwig

**Comment by hescherb** [comment]
Hallo Astrid

Sind Sie fähig, und interessiert, to schreibt mir a Javascript feld / 
link to kopieren in einen Joomla Content or User or Hikashop Feld

"Select as my vendor". By click copy VDI_aid to vendor_aid

I kann nicht unf finde niemand.

Alle gute

Herve Scherbyna

**Comment by astridx** [comment]
Ich verstehe nicht genau, was gemeint ist.

**Comment by hescherb** [comment]
Hallo Astrid

I habe Credential gepruft

Bitet können Sie etwas tun

Schönen Tag

Hervé



-------- Forwarded Message --------
Subject: 	Re: [astridx/pkg_agosms] I do not see the Tab "Show pin for 
articles" (#13)
Date: 	Mon, 23 Sep 2019 05:33:52 -0700
