### ISSUE TITLE
Wrong marker link to post

### ISSUE THREAD

**Issue by Polustr** [astridx/pkg_agosms#58]
Links to the posts in the marker popup looks like this 

option**s**=com_content&view=article&id=1

instead of

option=com_content&view=article&id=1

**Comment by astridx** [comment]
You are right, thank you. You mean https://github.com/astridx/pkg_agosms/blob/31c03764286fdbbdda0a84d3e243e0b6b86b633a/src/media/mod_agosm/js/agosm.js#L809, right?

I will correct it for the next version.

**Comment by Polustr** [comment]
Guten Tag Astrid,
Ja, genau das. Jetzt alles korrekt arbeiten.
Danke für Ihre Hilfe und nützliche Joomla-Erweiterungen!

**Comment by astridx** [comment]
Added in https://github.com/astridx/pkg_agosms/releases/tag/v1.0.90
