### ISSUE TITLE
"Special-Pin-Configuration" no further pins can be created anymore (?)

### ISSUE THREAD

**Issue by osm-frasch** [astridx/pkg_agosms#62]
I have set a lot of pins in the "Special-Pin-Configuration" area. So far this worked very well. 
Now I can't add any more when I click on the + sign. Could this be a bug or is there a limit to the number of pins?

I use Firefox (last current version). 
But I also tried this with Chrome in the last version. 
I have also disabled browser extensions like Privacy badger or uBlock for testing purposes

Joomla is also up to date (Joomla! 3.9.24, PHP version 7.3.25 )

It is about a map with 19 pins so far

Cheers & Thanks
Frank

**Comment by astridx** [comment]
What is your agosms Version?

**Comment by osm-frasch** [comment]
Version 1.0.27 installed 2019-01-19 
Is there a new out?

**Comment by astridx** [comment]
Please see https://github.com/astridx/pkg_agosms/releases

**Comment by osm-frasch** [comment]
Many thanks, last Version fix the problem

**Comment by astridx** [comment]
Thanks for the feedback
