### ISSUE TITLE
GeoJSON hinzufügen? - Add GeoJSON?

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#63]
Hey, ich habe leider keine Möglichkeit gefunden, eine GeoJSON Datei bzw. eine vergleichbare Datei hinzuzufügen um einen Bereich auf der Karte einzurahmen :( Gibt es das schlichtweg noch nicht oder habe ich das einfach übersehen?

Gruß

============

Hey, unfortunately I haven't found a way to add a GeoJSON file or a comparable file to frame an area on the map :( Does this simply not exist yet or did I just overlook it?

Greetings

**Comment by astridx** [comment]
Eine GeoJson Datei unterstützt meine Erweiterung bisher nicht. 
Ich habe das Hinzufügen von KLM-Dateien möglich gemacht, weil jemand POIs hierüber hinzufügen wollte. Ich selbst habe keine praktische Erfahrung mit KLM. Aber vielleicht ist das Markieren einer Stelle hierüber möglich?
    - - 
A GeoJson file does not support my extension so far. 
I made adding KLM files possible because someone wanted to add POIs via this. I myself have no practical experience with KLM. But maybe marking a location via this is possible?

**Comment by astridx** [comment]
Ich habe den Import einer GeoJSon Datei einmal auf die toDo liste gesetzt.
     - - 
 I have put the import of a GeoJSon file once on the toDo list.

**Comment by TheSoulrester** [comment]
Wie füge ich das denn mit einer kml Datei genau ein? 

Bisher habe ich das nämlich mit einer geojson eingebunden als reinen Quellcode in meiner Seite, würde aber das in dein Plugin transferieren.


Laut https://geojson.io/mobile.html#map=2/20.0/0.0 kann man auch eine Geophysik als kml speichern, jedoch soll wohl eine geheim deutlich dynamischer sein als eine kml?

Grus :)

**Comment by astridx** [comment]
Ich habe da Durcheinander gemacht. Entschuldigung. Das KML hatte ich hier nicht integriert.

Ich habe gerade den Anfang für GeoJSON getestet. https://github.com/astridx/pkg_agosms/releases/tag/v1.0.86 bietet ein Textfeld, in dem GeoJSON eingefügt werden kann.

![geojson](https://user-images.githubusercontent.com/9974686/111151037-30c58280-858f-11eb-842a-201557e4bdce.png)
Würde das reichen?

**Comment by TheSoulrester** [comment]
Ja, das würde reichen :)

bzw.: wäre auch ein einbinden einer lokalen geojson möglich? Leider scheint eine Modul-Komponente auf 65k Zeichen begrenzt zu sein, mein geojson hat jedoch knapp 78k Zeichen ;) (hier mal verlinkt: https://gist.github.com/TheSoulrester/b34826521c7aa934ea3901963711ad8e )

Darüber hinaus: habe jetzt mal eine kürzeren Inhalt einer geojson eingegeben und abgespeichert. jedoch wird der bereich noch nicht auf der karte eingezeichnet?


zudem erhalte ich einen fehler in der browser-konsole: 
`Uncaught TypeError: L.control.locate is not a function
    at agosm.js:776
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (agosm.js:5)`
    
    den erhalte ich aber auch, wenn ich das geojson - Feature deaktiviert habe

**Comment by astridx** [comment]
> Ja, das würde reichen :)
> 
> bzw.: wäre auch ein einbinden einer lokalen geojson möglich? Leider scheint eine Modul-Komponente auf 65k Zeichen begrenzt zu sein, mein geojson hat jedoch knapp 78k Zeichen ;) (hier mal verlinkt: https://gist.github.com/TheSoulrester/b34826521c7aa934ea3901963711ad8e )


Ich habe bei GeoJson ein Auswahl zwischen Textfeld und Datei eingebaut: https://github.com/astridx/pkg_agosms/releases/tag/v1.0.88

Das Hochladen der Datei erfolgt über den Medien-Manager. Hier muss in der globalen Konfiguration die Erweiterung `gson` erlaubt werden, wenn die Dateien mit `geojson` enden.

Schwerpunkt war bisher her die Funktion. Fehler fange ich noch nicht gut ab.  




> 
> Darüber hinaus: habe jetzt mal eine kürzeren Inhalt einer geojson eingegeben und abgespeichert. jedoch wird der bereich noch nicht auf der karte eingezeichnet?
> 
> zudem erhalte ich einen fehler in der browser-konsole:
> 
> ```
> Uncaught TypeError: L.control.locate is not a function 
> at agosm.js:776
> at NodeList.forEach (<anonymous>)
> at HTMLDocument.<anonymous> (agosm.js:5)
> ```
> 
> den erhalte ich aber auch, wenn ich das geojson - Feature deaktiviert habe

Ich glaub, dass hat nichts mit der neuen Funktion zu tun. Ich kann das aber leider nicht nachstellen. Hast du die Funktion  `Locate`  bei den allgemeinen Einstellungen zur Karte aktiviert? 
Theoretisch kann der Fehler nur vorkommen, wenn diese Funktion aktiviert ist und das JavaScript dazu nicht geladen ist.

**Comment by TheSoulrester** [comment]
Sieht schonmal super aus :)
![image](https://user-images.githubusercontent.com/7083599/111491956-9145f280-873c-11eb-9537-b0adf5ee3f98.png)

bzgl. dem oben genannten Fehler: keine Ahnung was da falsch war, hatte noch ein/zwei andere Komponenten (von dir?) bzgl. agosm in meiner testinstanz installiert. habe die einfach alle mal entfernt - und somit ist jetzt auch dieser fehler weg ;)

Gruß

**Comment by astridx** [comment]
GeoJson Upload added
![geojson](https://user-images.githubusercontent.com/9974686/111839209-be400400-88fa-11eb-91c8-3763eadd524f.png)
