### ISSUE TITLE
Mapbox - 410 Error

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#65]
GET https://api.tiles.mapbox.com/v4/mapbox.streets/13/4344/2782.png?access_token=_ZENSIERT_ 410 (Gone)

=> {"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}

**Comment by astridx** [comment]
Thanks, your are right: https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/

**Comment by astridx** [comment]
Corrected mapbox tilelayer in https://github.com/astridx/pkg_agosms/releases/tag/v1.0.90
