### ISSUE TITLE
OpenMapSurfer - Map not working

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#66]
Error in browser console

GET https://korona.geog.uni-heidelberg.de/tiles/roads/x=4343&y=2783&z=13 net::ERR_NAME_NOT_RESOLVED

**Comment by astridx** [comment]
Thanks, you are right. See https://wiki.openstreetmap.org/wiki/OpenMapSurfer

**Comment by astridx** [comment]
Deleted openMapSurfer with fallback to openstreetmap.org map in https://github.com/astridx/pkg_agosms/releases/tag/v1.0.90
