### ISSUE TITLE
Zoomlevel in "Kartenkonfiguration" of module not working

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#67]
The "Zoomlevel" setting is not  working as expected. only zoomlevel 19 works.

following things are enabled:
zoomlevel 12
stil: openstreetmap
scale: metric

pins of component "com_agosms", categorie "all groups" (in which all necessary markers are)
geojson enabled (file.geojson) 

other informations needed? please ask

**Comment by TheSoulrester** [comment]
if i am disabling pins of components, the zoomlevel settings works.

so there might be a problem with "pins of components"?

**Comment by astridx** [comment]
The Zoomlevel setting can be overridden by other functions - such as grouping or routing. Could it be that the pins/markers are so far away from each other that the grouping function changes the zoom to show them together?

**Comment by astridx** [comment]
I added a hint to the description, that the zoom level is overwritten from some other function in https://github.com/astridx/pkg_agosms/releases/tag/v1.0.90
![zoomlevelhint](https://user-images.githubusercontent.com/9974686/111838598-d95e4400-88f9-11eb-9e55-ab48d0eb7856.png)
.

**Comment by astridx** [comment]
So for you it was the settings, that is, that some settings revoke others?
I have no idea how to handle it better. There are already so many parameters, it confuses many people.

**Comment by TheSoulrester** [comment]
I dont really know if it was some setting that revoke the zoomlevel setting, but your explanation sounded promising. 

because when i deactivated the components pins and added the pins as single pins in the module, the zoomlevel took effect.

**Comment by astridx** [comment]
OK. Thanks. Then I close this issue, OK?

**Comment by astridx** [comment]
Yes, as already written. I don't fully understand the display problem yet. The alternative would be to hide the map and only make it possible to enter the coordinates via a text field. But I don't want that. That's why I live with the error. With a reload, the tiles are then displayed.
