### ISSUE TITLE
Disable "group" icon in map?

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#68]
Is it possible to disable this "group" feature if markers are very close together?
![image](https://user-images.githubusercontent.com/7083599/111771841-72ff0480-88ac-11eb-9ec7-04698ea97f9f.png)

**Comment by astridx** [comment]
Unfortunately, this is not possible at the moment. The user-defined setting of the grouping function is on the todo.

**Comment by astridx** [comment]
Add possibility to disable cluster at zoom level in https://github.com/astridx/pkg_agosms/releases/tag/v1.0.90
![disablecluster](https://user-images.githubusercontent.com/9974686/111839062-81740d00-88fa-11eb-8fb2-086f158c6ffc.png)
