### ISSUE TITLE
Mapbox - {"message":"Not Found"}

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#74]
With the newly released version (1.0.92), mapbox is not working: 

`1392.png:1 GET https://api.tiles.mapbox.com/v4/mapbox.streets/12/2172/1392.png?access_token=<ACCES-KEY> 410 (Gone)`

=> {"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}

I think you had fixed this in https://github.com/astridx/pkg_agosms/issues/65

**Comment by astridx** [comment]
Yes, I had that. For me, the mapbox tiles in the search module are also now displayed correctly.
Where exactly does the error occur?

**Comment by TheSoulrester** [comment]
oh sorry, 

this occours in the frontend

could it be that you uploaded an outdated release file?

geojson is also removed: 
![image](https://user-images.githubusercontent.com/7083599/112888678-f4d50600-90d4-11eb-966c-b2f5d11006c9.png)

**Comment by astridx** [comment]
Did it work wird version 1.0.90 and the problem occures after the updated?

**Comment by TheSoulrester** [comment]
Yes, with the version before the todays updates, geojson as well as Mapbox worked without any issues

**Comment by astridx** [comment]
I am sorry you are having problems.

I can't reproduce the problem with Mapbox. but I have just fixed a bug with the language files. Would you please test the  version x.93. Maybe it will solve the mapbox problem:
https://github.com/astridx/pkg_agosms/releases

**Comment by TheSoulrester** [comment]
strange. now the tab geojson is available again, but without any "readable" text ;) - only your variables are shown
![image](https://user-images.githubusercontent.com/7083599/113008945-cceaae80-9177-11eb-8399-f4017ac428cc.png)

but mapbox now works. but: first mapbox gave me a 404 error. i changed to openstreetmap, saved and then switched again to mapbox. only then mapbox worked as expected.

**Comment by astridx** [comment]
Sorry, i will fix this with the next version.A quick solution is to delete the file

language/de-DE/de-DE.mod_agosm.ini
or/and 
language/en-GB/en-GB.mod_agosm.ini

**Comment by astridx** [comment]
The language string is correct again here:
https://github.com/astridx/pkg_agosms/releases/tag/v1.0.97

It would be nice if you could confirm this briefly.

**Comment by TheSoulrester** [comment]
hi, 
yes, with 1.0.98 the missing language strings are back again ;)
