### ISSUE TITLE
Problem/Question to geojson properties

### ISSUE THREAD

**Issue by escuco** [astridx/pkg_agosms#75]
Hello!

I'm going to use this very cool module to encircle the area of a flea market and mark the participants on the streets (not with pins, but with lines) via geoJSON.

I'm drawing the objects and generating the code on geojson.io. You can see a example of the code and the output here: 
https://gist.github.com/escuco/7d14ce6046f5032bb961160c79cdc498

When I paste the geoJSON output into the geoJSON object field from this module, the objects are pretty drawn, but some of the properties are not taken over:
https://flohmarkt-uelsen.de/index.php/flohmarktplan-strassenkarte

As you can see, all the lines (area border and street marker) are blue and with the same thickness. But the border of the market area should be in black and with a stroke width of 1.3. 
The two small marker lines (in Birkenweg and Kiefernweg) seems ok (color blue and stroke width 4).
You can see the difference, if you compare the two links.

This isn't a problem for my small project and I'm glad I can use this very nice module anyway, but I'm curious what might be the cause. Maybe it's a leaflet thing?

**Comment by astridx** [comment]
@escuco 
Thank you for pointing this out.
So far I support the property "geometry". I do not yet support the "properties for geoJSON".
I should have explained that more precisely, sorry for that.
I am currently considering whether and how to implement the "properties".
I will leave this issue open as a reminder.

**Comment by escuco** [comment]
Thank you! 
Nevertheless, your plugin is more than helpful.

**Comment by astridx** [comment]
No I support the properties
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke": "#000000",
        "stroke-width": 1.3,
        "stroke-opacity": 1,
        "fill": "#00ff1e",
        "fill-opacity": 0.1
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
...
...      
```

Perhaps you like to test:
https://github.com/astridx/pkg_agosms/releases/tag/v1.0.100

**Comment by escuco** [comment]
Yay!
What I can see after the update: It works perfect! Now I'm going to make some finetuning to my map properties.
Thanks very much!
