### ISSUE TITLE
Language strings missing - Joomla 4

### ISSUE THREAD

**Issue by drmenzelit** [astridx/pkg_agosms#82]
Installed Agosm on a fresh Joomla 4 site, several language strings are missing:

![grafik](https://user-images.githubusercontent.com/9153168/152499308-8f37c6a3-92d9-48b7-99ac-1817e1295977.png)

Some of them are present on the language files from component / module, but Joomla seems to don't recognize / find them.

**Comment by astridx** [comment]
Thank you. I have now included the strings in the component.
They will be correct in the next release

https://github.com/astridx/pkg_agosms/blob/26fad545b5b7f805bfd82bfa708b7643aa6133a7/j4/pkg_agosms/src/administrator/components/com_agosms/language/en-GB/com_agosms.ini#L51
