### ISSUE TITLE
Backend Issue: No map is shown

### ISSUE THREAD

**Issue by Gustel** [astridx/pkg_agosms#83]
I am working on a local test-environment (Apache/2.4.46 (Win64) PHP/7.4.1RC1/Joomla 4.1). After installing Agosm 4.0.6 I tried to configure an AGOSM Module. But unfortunately there is no map shown at all. Whether in tab "Kartenkonfiguration" nor in "Spezielle Pin-Konfiguration". I entered on both tabs the coordinates "53.013, 9.012" (it's a place near Bremen, Germany), saved the module, but still no map appears. On the frontend everything seems to be okay. On another Joomla-Installation (Joomla 3.10.6 and Agosm 3.0.3) everything works fine. Any idea?
By the way: when I try to open the "Agosm Search Module (Experimental)" in Agosm 4.0.6 it ends with the error "Call to undefined method Joomla\CMS\Application\AdministratorApplication::isSite()".

**Comment by astridx** [comment]
Do I understand correctly that you see the map in the frontend but not in the backend? 
Do you see error messages in the browser console in the backend?
Thank you for the hint. The error in the module will be corrected in the next release.

**Comment by Gustel** [comment]
Sorry, to close this issue was an accident.

**Comment by astridx** [comment]
I didn't mean PHP errors that Joomla displays, but JavaScript errors that are displayed in the browser console (Web Developer Tools):

https://en.wikipedia.org/wiki/Web_development_tools

Are there any errors here?

**Comment by Gustel** [comment]
Hello Astrid,

 

thanks for your reply. There are no errors displayed in the browser console (look the attached screenshot). The homepage is now online again, and there is also a test environment on bplaced. Since the problem is everywhere, I could set up administrator access for you for the test environment. But for that I would have to know where I could send you the login data.

 

Kind regards

Gustel

 

Von: Astrid ***@***.***> 
Gesendet: Sonntag, 3. April 2022 15:40
An: astridx/pkg_agosms ***@***.***>
Cc: Gustel ***@***.***>; State change ***@***.***>
Betreff: Re: [astridx/pkg_agosms] Backend Issue: No map is shown (Issue #83)

 

I didn't mean PHP errors that Joomla displays, but JavaScript errors that are displayed in the browser console (Web Developer Tools):

https://en.wikipedia.org/wiki/Web_development_tools

Are there any errors here?

**Comment by astridx** [comment]
Are you still having problems with the latest version https://github.com/astridx/pkg_agosms/releases/tag/v4.0.15?

**Comment by astridx** [comment]
Sorry my mistake. Would you please check again with this version: https://github.com/astridx/pkg_agosms/releases/tag/v4.0.16
(I did not add joomla updater yet. You have do donwload this version)

**Comment by Gustel** [comment]
Hello Astrid,
now, with version 4.0.16, everything works fine! Many thanks for your effort.
Regards
Gustel
