### ISSUE TITLE
No SEF url to article

### ISSUE THREAD

**Issue by drmenzelit** [astridx/pkg_agosms#91]
I have created a category with articles which should be used as markers in the map. A custom field agosmaddressmarker was created to store the location. The map module is configured to display markers from an articles category. The articles are also linked to a blog layout menu. The marker appears in the map and it its linked to the article, but the url is `/index.php?option=com_content&view=article&id=2` instead of `/denkmalobjekte/klosterkirche`. It is possible to have nice urls in the map?

**Comment by astridx** [comment]
I think that is certainly possible. So far it is hard coded here. 
https://github.com/astridx/pkg_agosms/blob/ae39135db9173adf8981d9822bbefc0c8e7df95e/j4/pkg_agosms/src/media/mod_agosm/js/agosm.js#L959
I write it on my todo list. If someone with better Joomla router knowledge is faster I am happy about a PR

**Comment by astridx** [comment]
If it's still interesting for you. In version 4.0.15 you can create a popup text per item by linking a custom field to it - analogous to the field used to calculate a coordinate from an address. You can specify an <a> tag with an href url if you choose a texarea with filter raw.
This is not optimal, but I can't find a good general solution to your question. If I understand correctly, there are so many special cases that I don't want to hard code. Someone may want to display an article-alias directly with no category using the alias in the ULR, or they might want to link to a URL from tags or featured...
