### ISSUE TITLE
Menu item "Create a new Agosm"

### ISSUE THREAD

**Issue by bettinhelen** [astridx/pkg_agosms#99]
Hello
and thank you for providing the extension!
I am testing the extension local on my computer and I use Joomla 4 with the current Agosm.
My problem: Menu item "Create a new Agosm" causes error message that I don't understand. Debug modus is on, but I get no more information. 
<img width="889" alt="Bildschirmfoto 2022-05-11 um 21 36 06" src="https://user-images.githubusercontent.com/25564696/168053204-e03f6c84-661b-46f1-ba40-3b4d3bf26d70.png">

Kind Regards
Bettina

**Comment by astridx** [comment]
Oops, maybe I got something mixed up when creating examples for showing use cases.

I'll take a closer look when I have more time.

**Comment by bettinhelen** [comment]
Maybe this little bug caused the error: 
components/com_agosms/language/de-DE/com_agosms.ini
-> on line 39 the first letter was missing
Now I can create an AGOSM in FE
